### ISSUE TITLE
Support for Django 3.0?

### ISSUE THREAD

**Issue by HealperRasmus** [wildfish/django-gdpr-assist#19]
Hi. Great project you guys have here. Are there any plans for adding support for Django 3.0 to this project?

**Comment by radiac** [comment]
Thanks! Yes, we plan to push a new release with this shortly. We'll update this issue when it's ready.

**Comment by HealperRasmus** [comment]
Excellent! 
Would it be possible to get a super rough estimate on when it is ready? (If it is more than ½ year, I might need to look after an alternative solution)

**Comment by radiac** [comment]
I think we should get onto this within the next couple of weeks.

**Comment by HealperRasmus** [comment]
That sounds awesome 👍

**Comment by radiac** [comment]
The master branch has Django 3 support, but we're holding off pushing to pypi for a few more days until we can do more testing. If you'd like to consider it a beta release and give it a try, any feedback is welcome! Will update this issue when it's released to pypi.

**Comment by radiac** [comment]
Thanks for waiting! Version 1.3.0 is out on pypi. There were some database changes in 1.2.0, so do read the upgrade instructions to get migrations in the right order.

**Comment by HealperDK** [comment]
Awesome. Thanks so much for the awesome work! :)
