### ISSUE TITLE
Anonymising breaks for models with UUID primary key

### ISSUE THREAD

**Issue by fronbasal** [wildfish/django-gdpr-assist#26]
Hello!
Unfortonately `django-gdpr-assist` does not play nicely with models that have a UUID primary key.
The resulting issue is, that the library will attempt to parse the pk as an integer and thus the database commit fails, because the "integer" (casted UUID) is too large.

**Comment by fronbasal** [comment]
The resulting end of the tracestack looks like this:
```    return self.cursor.execute(sql, params)
django.db.utils.DataError: integer out of range```

**Comment by jamesoutterside** [comment]
Hi @fronbasal 

Sorry for the delay in replying to this. We've taken a look and are looking to add support for alternate PK fields for the next release. 

Thanks for the report!

**Comment by fronbasal** [comment]
Awesome! Thank you for the PR. Great project!
