### ISSUE TITLE
PrivacyMeta docs issue

### ISSUE THREAD

**Issue by montag** [wildfish/django-gdpr-assist#4]
FYI, the docs specify the method to manually register a model as:

`gdpr_assist.register_model(User, UserPrivacyMeta)`

However, it seems the correct way is with:

`gdpr_assist.registry.register(User, UserPrivacyMeta)`

Is that the correct way, or am I missing something?

**Comment by radiac** [comment]
That is the way to do it, but there is also a convenience wrapper for it at `gdpr_assist.register(Model, UserPrivacyMeta)`.

Looks like the docs have the wrong function name - I'll update it now for the next release. Thanks for spotting it and letting us know!
