### ISSUE TITLE
Upgrading from 1.3 to 1.4

### ISSUE THREAD

**Issue by HealperDK** [wildfish/django-gdpr-assist#59]
Hi. After updating to version 1.4.0 I started receiving this error when starting django:

RuntimeError: Registered gdpr_assist model Users manager specified 'use_in_migrations=True', with no name provided.

Is there a guide on what changes need to be done in order to upgrade to version 1.4.0?

**Comment by jamesoutterside** [comment]
Hi @HealperDK 

Apologies, while there is a note in the docs (https://django-gdpr-assist.readthedocs.io/en/latest/privacy_meta.html?highlight=use_in_migrations#registering-manually) we should probably bring this higher up/make clearer. 

Hope that helps. Will leave this open until the docs are improved. 

Thanks
