### ISSUE TITLE
What about unique and non-empty/non-null fields?

### ISSUE THREAD

**Issue by bnisevic** [wildfish/django-gdpr-assist#9]
What happens with fields which has unique constraint or they can not be empty?

**Comment by radiac** [comment]
At the moment we don't detect or do anything special for them automatically, but you can create a custom anonymiser: https://django-gdpr-assist.readthedocs.io/en/latest/privacy_meta.html#anonymise-field-name-self-instance

For example:
```
class MyModel(models.Model):
    slug = models.SlugField(unique=True)

    class PrivacyMeta:
        def anonymise_slug(self, instance):
            instance.slug = f"slug-{instance.pk}"
```
